CREATE DATABASE IF NOT EXISTS WAGES_CPI;

CREATE SCHEMA IF NOT EXISTS WAGES_CPI.RAW;

CREATE SCHEMA IF NOT EXISTS WAGES_CPI.ANALYTICS;

CREATE OR REPLACE FILE FORMAT WAGES_CPI.RAW.csv_format
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE WAGES_CPI.RAW.my_stage
FILE_FORMAT = WAGES_CPI.RAW.csv_format;

CREATE OR REPLACE TABLE WAGES_CPI.RAW.economic_data (
    date STRING,
    cpi FLOAT,
    wage FLOAT,
    country STRING
);

SELECT COUNT(*) FROM WAGES_CPI.RAW.economic_data;

SELECT * FROM WAGES_CPI.RAW.economic_data LIMIT 10;