CREATE OR REPLACE TABLE WAGES_CPI.ANALYTICS.MONTHLY_CPI_USA AS
SELECT
    TO_DATE(date || '-01') AS month_date,
    cpi,
    country
FROM WAGES_CPI.RAW.economic_data
WHERE country = 'USA'
ORDER BY month_date;

CREATE OR REPLACE TABLE WAGES_CPI.ANALYTICS.ANNUAL_WAGES_CPI_USA AS
SELECT
    YEAR(TO_DATE(date || '-01')) AS year,
    ROUND(AVG(wage), 2) AS avg_annual_wage,
    ROUND(AVG(cpi), 3) AS avg_annual_cpi,
    country
FROM WAGES_CPI.RAW.economic_data
WHERE country = 'USA'
GROUP BY YEAR(TO_DATE(date || '-01')), country
ORDER BY year;

SELECT * 
FROM WAGES_CPI.ANALYTICS.MONTHLY_CPI_USA
LIMIT 10;

SELECT * 
FROM WAGES_CPI.ANALYTICS.ANNUAL_WAGES_CPI_USA;

SELECT COUNT(*) AS total_rows
FROM WAGES_CPI.ANALYTICS.MONTHLY_CPI_USA;

SELECT COUNT(*) AS total_years
FROM WAGES_CPI.ANALYTICS.ANNUAL_WAGES_CPI_USA;